In [15]:
#import the numerical python(numpy) package
import numpy as np

#creating a 3*3 matrix array
print("Given Matrix is")
matrix = np.array([[2,4,-8],[3,-7,9],[5,7,1]])

#printing the matrix array
print(matrix)
print()

#inverse matrix
print("inverse of the given matrix is")
invmat = np.linalg.inv(matrix)
print(invmat)
print()

#to check if the inverse matrix obtained is correct,we just need to multiply our matrix array and inverse matrix to get identity matrix(3*3) as the output.
print("identity matrix obtained when matrix is multiplied with its inverse")
a = np.matmul(matrix , invmat)
print(a)


Given Matrix is
[[ 2  4 -8]
 [ 3 -7  9]
 [ 5  7  1]]

inverse of the given matrix is
[[ 0.16666667  0.14285714  0.04761905]
 [-0.1        -0.1         0.1       ]
 [-0.13333333 -0.01428571  0.06190476]]

identity matrix obtained when matrix is multiplied with its inverse
[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [-2.77555756e-17  1.00000000e+00  1.11022302e-16]
 [-2.77555756e-17 -4.68375339e-17  1.00000000e+00]]


In [ ]:
()